apiVersion: apps/v1
kind: Deployment
metadata:
  name: PartyManagement
  labels:
    app: PartyManagement
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PartyManagement
  template:
    metadata:
      labels:
        app: PartyManagement
    spec:
      containers:
        - name: PartyManagement
          image: username/PartyManagement:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5